baseURL = "http://www.codeisscience.com/"
languageCode = "en-gb"
title = "Code Is Science"
theme = "codeisscience"
publishDir = "docs"
disableKinds= ["taxonomy"]
taxonomies= false
[params]
  description = "Working with the scientific coding community to champion Open Source code, helping to ensure code is peer reviewed and FAIR."
  iconsTitle = "Icomoon"
  iconsLink = "https://icomoon.io/"
  hugoTitle = "Hugo"
  hugoLink = "https://gohugo.io/"
